// Generated by https://quicktype.io
import 'package:json_annotation/json_annotation.dart';

part 'movies_cast_list.g.dart';

@JsonSerializable()
class MovieCastList {
  int id;
  List<Cast> cast;
  List<Crew> crew;

  MovieCastList({
    this.id,
    this.cast,
    this.crew,
  });

  factory MovieCastList.fromJson(Map<String, dynamic> json) =>
      _$MovieCastListFromJson(json);
}

@JsonSerializable()
class Cast{
  @JsonKey(name: "cast_id")
  int castId;
  String character;
  @JsonKey(name: "credit_id")
  String creditId;
  int gender;
  int id;
  String name;
  int order;
  @JsonKey(name: "profile_path")
  String profilePath;

  Cast({
    this.castId,
    this.character,
    this.creditId,
    this.gender,
    this.id,
    this.name,
    this.order,
    this.profilePath,
  });

  factory Cast.fromJson(Map<String, dynamic> json) => _$CastFromJson(json);
}

@JsonSerializable()
class Crew {
  @JsonKey(name: "credit_id")
  String creditId;
  String department;
  int gender;
  int id;
  String job;
  String name;
  @JsonKey(name: "profile_path")
  String profilePath;

  Crew({
    this.creditId,
    this.department,
    this.gender,
    this.id,
    this.job,
    this.name,
    this.profilePath,
  });

  factory Crew.fromJson(Map<String, dynamic> json) => _$CrewFromJson(json);
}
